In [ ]:
# Imports
from scipy.fft import fft
import numpy as np

Zadanie 5. Oblicz dyskretną transformatę Fouriera sygnału x = [1, 2, 1, 1].

In [9]:
x = np.array([1, 2, 1, 1])

dft_result = np.fft.fft(x)

print(dft_result)


[ 5.+0.j  0.-1.j -1.+0.j  0.+1.j]


Zadanie 6. Wykonaj transformatę Fouriera podanych sygnałów korzystając z
funkcji fft(x)(Fast Fourier Transform) oraz ifft(x)(Inverse Fast Fourier Transform).
• [4, 3, 7, 3]
• [2, 3, 4, 1, 5]
• [1, 3, 4, 6, −9, 0, 0, 0]
Zauważ, że dla sygnału rzeczywistego transformata może być zespolona

In [3]:
x = np.array([1.0, 2.0, 1.0, -1.0, 1.5])

fft(x)

array([ 4.5       -0.j        ,  2.08155948-1.65109876j,
       -1.83155948+1.60822041j, -1.83155948-1.60822041j,
        2.08155948+1.65109876j])

In [4]:
x = np.array([4, 3, 7, 3])

fft(x)

array([17.-0.j, -3.+0.j,  5.-0.j, -3.-0.j])

In [5]:
x = np.array([2, 3, 4, 1, 5])

fft(x)

array([15.        -0.j        ,  0.42705098+0.13875728j,
       -2.92705098+4.02874005j, -2.92705098-4.02874005j,
        0.42705098-0.13875728j])

In [7]:
x = np.array([1, 3, 4, 6, -9, 0, 0, 0])

fft(x)

array([  5.         -0.j        ,   7.87867966-10.36396103j,
       -12.         +3.j        ,  12.12132034 -2.36396103j,
       -13.         -0.j        ,  12.12132034 +2.36396103j,
       -12.         -3.j        ,   7.87867966+10.36396103j])